<?xml version="1.0" encoding="UTF-8"?><testsuite name="wy_auto_test" tests="1" errors="1" failures="0" skip="0"><testcase test_method="TestCases.ApiCases.RongheInterface.test_p0_ronghe_three.test_get_List3_topic" name="获取节目单信息 ：正常" time="1.049"><error type="requests.exceptions.ConnectionError" message="('Connection aborted.', error(10061, ''))&#10;-------------------- &gt;&gt; begin captured stdout &lt;&lt; ---------------------&#10;ERROR&#10;&#10;--------------------- &gt;&gt; end captured stdout &lt;&lt; ----------------------"><![CDATA[  File "C:\Python27\lib\unittest\case.py", line 327, in run
    testMethod()
  File "C:\Python27\lib\site-packages\nose\case.py", line 207, in runTest
    self.test(*self.arg)
  File "D:\wy_auto\TestCases\ApiCases\RongheInterface\test_p0_ronghe_three.py", line 85, in test_get_List3_topic
    common_itemconfig_result = Common.revoke_get_request(url, data)
  File "D:\wy_auto\Controller\Api\Common.py", line 52, in revoke_get_request
    response= requests.get(url, data = data).content
  File "C:\Python27\lib\site-packages\requests\api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
('Connection aborted.', error(10061, ''))
-------------------- >> begin captured stdout << ---------------------
ERROR

--------------------- >> end captured stdout << ----------------------]]></error><system-out>ERROR
</system-out></testcase></testsuite>